package br.ufc.pds.view;

import br.ufc.pds.controller.ControlBancoImobiliario;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class SelecionarQuantidadeDeJogadoresPanel {
    private JPanel PainelPrincipal;
    private JComboBox quantidadeJogadoresCCbox;
    private JButton button1;
    private String quantidadeJogadores;
    private static JFrame frame = new JFrame("App");

    public SelecionarQuantidadeDeJogadoresPanel() {
        quantidadeJogadoresCCbox.setSelectedIndex(0);

        quantidadeJogadoresCCbox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                quantidadeJogadores = (String) quantidadeJogadoresCCbox.getSelectedItem();
                ControlBancoImobiliario.getInstance().setNumJogadores(Integer.parseInt(quantidadeJogadores.split(" ")[0]));
            }
        });
        button1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int qtd = Integer.parseInt(quantidadeJogadores.split(" ")[0]);
                JOptionPane.showMessageDialog(null, qtd);
                ControlBancoImobiliario.getInstance().changeHasSetedNumJogadores();
                frame.dispose();
            }
        });
    }

    public void run() {
        frame.setContentPane(new SelecionarQuantidadeDeJogadoresPanel().PainelPrincipal);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        PainelPrincipal = new JPanel();
        PainelPrincipal.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        PainelPrincipal.setAlignmentX(1.0f);
        PainelPrincipal.setAlignmentY(1.0f);
        PainelPrincipal.setMinimumSize(new Dimension(500, 200));
        PainelPrincipal.setOpaque(true);
        PainelPrincipal.setPreferredSize(new Dimension(500, 200));
        PainelPrincipal.putClientProperty("html.disable", Boolean.FALSE);
        final JLabel label1 = new JLabel();
        label1.setText("Selecione uma quantidade de jogadores");
        PainelPrincipal.add(label1);
        quantidadeJogadoresCCbox = new JComboBox();
        quantidadeJogadoresCCbox.setEditable(false);
        quantidadeJogadoresCCbox.setMinimumSize(new Dimension(200, 30));
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("2 jogadores");
        defaultComboBoxModel1.addElement("3 jogadores");
        defaultComboBoxModel1.addElement("4 jogadores");
        defaultComboBoxModel1.addElement("5 jogadores");
        defaultComboBoxModel1.addElement("6 jogadores");
        quantidadeJogadoresCCbox.setModel(defaultComboBoxModel1);
        quantidadeJogadoresCCbox.setPreferredSize(new Dimension(200, 30));
        quantidadeJogadoresCCbox.setSelectedIndex(1);
        PainelPrincipal.add(quantidadeJogadoresCCbox);
        button1 = new JButton();
        button1.setPreferredSize(new Dimension(450, 30));
        button1.setText("Confirmar");
        PainelPrincipal.add(button1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PainelPrincipal;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
